// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DrawListAt(arg1) {
  return window['go']['main']['App']['DrawListAt'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function SaveExportedVideo(arg1, arg2) {
  return window['go']['main']['App']['SaveExportedVideo'](arg1, arg2);
}
