// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {drawlist} from '../models';
import {main} from '../models';

export function AudioBytes():Promise<Array<number>>;

export function DrawListAt(arg1:number):Promise<Array<drawlist.Instance>>;

export function OpenProject(arg1:string):Promise<main.ProjectInfo>;

export function SaveVideoAs(arg1:Array<number>,arg2:string):Promise<string>;
